#!/usr/bin/env bash
# information about sub domains
display_info ()
{
    domain="$1"
    subdomain="$2"
    echo -n "The subdomain $2"
    dig "$subdomain.$domain" | grep -A1 "ANSWER SECTION:" | tail -n1 | awk '{print " is a " $4 " record and points to " $5}'
}

if [ "$#" == 1 ]
then
    for subdomain in www lb-01 web-01 web-02; do
        display_info "$1" "$subdomain"
    done
else
    display_info "$1" "$2"
fi
