#!/usr/bin/env bash
# Installing & configuring load balancer
sudo apt-get install -y software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-1.8
sudo apt-get -y update
sudo apt-get -y install haproxy=1.8.\*
echo "ENABLED=1" >> /etc/default/haproxy
sed -i "$ a \listen holberton\n\tbind *:80\n\tmode http\n\tstats enable\n\tbalance roundrobin" /etc/haproxy/haproxy.cfg
sed -i "$ a \\\tserver 1579-web-01 34.75.41.244:80 check\n\tserver 1579-web-02 54.227.21.96:80 check" /etc/haproxy/haproxy.cfg
sudo service haproxy start
