#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times

i=0

while (( i <= 10))
do
    if (( i == 9 ));
    then
	echo "Hi"
	(( i++ ))
	else
		echo "Holberton School"
		(( i++ ))
	fi
done
